width            = 27.0;
depth            = 37.0;
d_factor         = 0.4;
radius           = 8.0;

loop_thickness_1 = 0.8;
loop_thickness_2 = 1.5;
loop_height_1    = 1.5;
loop_height_2    = 0.5;

knob_height_1    = 2.7;
knob_height_2    = 1.3;
knob_diameter_1  = 2.4;
knob_diameter_2  = 4.0;

trafo_width      = 16.2;
trafo_depth      = 26.2;
trafo_radius     =  3.5;
trafo_height     = 31.6;

blade_radius     =  5.0;
blade_position   =  3.0;
blade_height     = 27.7;
blade_thickness  =  0.8;
blade_pitch      =  2.0;
blade_pitch2     =  7.0;
